export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>CustomerPortal</title>
  <base href="/PrimaUI/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">input[id^=txtCode][_ngcontent-ng-c1561885769]{width:40px;margin:2px}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click","input","compositionstart","compositionend","keydown","paste","drop"],["blur"]);</script>
  <app-root ng-version="20.0.0" ngh="1" ng-server-context="ssg"><div><h3><u>Angular 20 Application</u></h3></div><a href="/PrimaUI/otppage" jsaction="click:;">OTP Page</a>&nbsp;|
<a href="/PrimaUI/page2" jsaction="click:;">Page2</a>&nbsp;|
<a href="/PrimaUI/page3" jsaction="click:;">Page3</a>&nbsp;
<hr><router-outlet></router-outlet><app-page1 _nghost-ng-c1561885769 ngh="0"><div _ngcontent-ng-c1561885769 class="col-md-12"><div _ngcontent-ng-c1561885769 class="passcode-wrapper"><br _ngcontent-ng-c1561885769><input _ngcontent-ng-c1561885769 id="txtCode1" type="tel" inputmode="numeric" pattern="[0-9]*" maxlength="1" autocomplete="one-time-code" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;keydown:;paste:;drop:;"><input _ngcontent-ng-c1561885769 id="txtCode2" type="tel" inputmode="numeric" pattern="[0-9]*" maxlength="1" autocomplete="one-time-code" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;keydown:;paste:;drop:;"><input _ngcontent-ng-c1561885769 id="txtCode3" type="tel" inputmode="numeric" pattern="[0-9]*" maxlength="1" autocomplete="one-time-code" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;keydown:;paste:;drop:;"><input _ngcontent-ng-c1561885769 id="txtCode4" type="tel" inputmode="numeric" pattern="[0-9]*" maxlength="1" autocomplete="one-time-code" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;keydown:;paste:;drop:;"><input _ngcontent-ng-c1561885769 id="txtCode5" type="tel" inputmode="numeric" pattern="[0-9]*" maxlength="1" autocomplete="one-time-code" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;keydown:;paste:;drop:;"><input _ngcontent-ng-c1561885769 id="txtCode6" type="tel" inputmode="numeric" pattern="[0-9]*" maxlength="1" autocomplete="one-time-code" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;keydown:;paste:;drop:;"></div><p _ngcontent-ng-c1561885769>OTP Value: </p><div _ngcontent-ng-c1561885769><br _ngcontent-ng-c1561885769><button _ngcontent-ng-c1561885769 style="display: inline-block; margin-right: 10px;" jsaction="click:;">Submit</button><button _ngcontent-ng-c1561885769 style="display: inline-block;" jsaction="click:;">Reset</button></div></div></app-page1><!----></app-root>
<script src="main-JEY3KJQ7.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"14":[{"i":"c1561885769","r":1}]}}]}</script></body></html>`;